/* preset.c
 * Greg Cook, 6/Feb/2017
 */

/* CRC RevEng: arbitrary-precision CRC calculator and algorithm finder
 * Copyright (C) 2010, 2011, 2012, 2013, 2014, 2015, 2016, 2017
 * Gregory Cook
 *
 * This file is part of CRC RevEng.
 *
 * CRC RevEng is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * CRC RevEng is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with CRC RevEng.  If not, see <https://www.gnu.org/licenses/>.
 */

/* 2017-02-06: munpack() produces canonical models
 * 2017-02-05: added magic field
 * 2017-02-01: added CRC-64/GO-ISO, 2 new aliases
 * 2016-07-26: added array order checking code
 * 2016-07-25: added 5 new algorithms
 * 2016-07-14: added CRC-16/CMS
 * 2016-07-08: added CRC-16/PROFIBUS
 * 2016-02-23: added 11 new algorithms, 4 new aliases
 * 2016-02-22: split off from model.c
 * 2016-02-22: preset points to primary alias, eliminated strcmp()
 * 2016-02-22: eliminated bogus calls to bsearch()
 * 2015-07-29: eliminated struct malias.isprimry
 * 2014-01-14: added CRC-8/DVB-S2
 * 2014-01-11: corrected CRC-40/GSM, added alias CRC-8/AES
 * 2013-10-14: added CRC-13/BBC and six cdma2000 algorithms
 * 2013-06-11: ensure BMP_BIT is an integer constant to compile presets
 * 2013-01-20: big polynomials autogenerated, corrected CRC-82/DARC
 * 2012-07-19: added CRC-8/EBU
 * 2012-07-16: added CRC-15/MPT1327
 * 2012-05-25: removed CRC-1/PARITY-EVEN, CRC-1/PARITY-ODD
 * 2012-04-12: added model CRC-31/PHILIPS
 * 2012-02-20: corrected model CRC-6/DARC
 * 2011-08-28: added model CRC-64/XZ
 * 2011-04-30: added models CRC-16/TMS37157 and CRC-A, and alias CRC-B
 * 2011-02-10: made preset models ANSI C compliant
 * 2011-01-17: fixed ANSI C warnings (except preset models)
 * 2011-01-01: added mbynum(), mcount()
 * 2010-12-26: renamed CRC RevEng
 * 2010-12-18: minor change to mtostr() output format
 * 2010-12-15: added mcmp(), mmatch()
 * 2010-12-14: finished mbynam(), mnames()
 * 2010-12-13: restarted with PCONST macros
 * 2010-12-12: was having so much fun I didn't think to try compiling. :(
 * 2010-12-12: started models.c
 */

#include <ctype.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include "reveng.h"

/* Private declarations */

/* incomplete type declaration to permit cross-reference */
struct malias;

struct mpreset {
	const unsigned long width;		/* width of CRC algorithm */
	const bmp_t *const bspoly;		/* polynomial with highest-order term removed. length determines CRC width */
	const bmp_t *const binit;		/* initial register value. length == poly.length */
	const int flags;			/* P_REFIN and P_REFOUT indicate reflected input/output */
	const bmp_t *const bxorout;		/* final register XOR mask. length == poly.length */
	const bmp_t *const bcheck;		/* optional check value, the CRC of the UTF-8 string "123456789" */
	const bmp_t *const bmagic;		/* optional magic check value, the residue of a valid codeword */
	const struct malias *const alias;	/* optional canonical name of the model */
};

struct malias {
	const char *name;			/* name of alias */
	const struct mpreset *const model;	/* corresponding model */
};

#ifdef PRESETS
#  if BMP_BIT < 32
#    error config.h: BMP_BIT must be an integer constant macro to compile presets
#  else /* BMP_BIT */

/* Big polynomial constants. */

/* Directives for relink.pl */
/* CONSTANT b40  = (40, 0x0004820009) */
/* CONSTANT b40a = (40, 0xffffffffff) */
/* CONSTANT b40b = (40, 0xd4164fc646) */
/* CONSTANT b40c = (40, 0xc4ff8071ff) */
/* CONSTANT b64  = (64, 0x000000000000001b) */
/* CONSTANT b64a = (64, 0xffffffffffffffff) */
/* CONSTANT b64b = (64, 0xb90956c775a41001) */
/* CONSTANT b64c = (64, 0x5300000000000000) */
/* CONSTANT b64d = (64, 0x42f0e1eba9ea3693) */
/* CONSTANT b64e = (64, 0x6c40df5f0b497347) */
/* CONSTANT b64f = (64, 0x62ec59e3f1a4f00a) */
/* CONSTANT b64g = (64, 0xfcacbebd5931a992) */
/* CONSTANT b64h = (64, 0x995dc9bbdf1939fa) */
/* CONSTANT b64i = (64, 0x49958c9abd7d353f) */
/* CONSTANT b82  = (82, 0x0308c0111011401440411) */
/* CONSTANT b82a = (82, 0x09ea83f625023801fd612) */

/* The next section was generated by relink.pl from the directives above. */

/* DO NOT EDIT the section below, INCLUDING the next comment. */
/* BEGIN AUTO-GENERATED CONSTANTS */
#    if BMP_BIT >= 40
static const bmp_t b40[] = {
	BMP_C(0x0004820009) << (BMP_BIT - 40),
};
static const bmp_t b40a[] = {
	BMP_C(0xffffffffff) << (BMP_BIT - 40),
};
static const bmp_t b40b[] = {
	BMP_C(0xd4164fc646) << (BMP_BIT - 40),
};
static const bmp_t b40c[] = {
	BMP_C(0xc4ff8071ff) << (BMP_BIT - 40),
};
#    else /* BMP_BIT */
static const bmp_t b40[] = {
	BMP_C(0x00048200) << (BMP_BIT - 32) | BMP_C(0x04) >> (39 - BMP_BIT),
	BMP_C(0x09) << (BMP_BIT * 2 - 40),
};
static const bmp_t b40a[] = {
	BMP_C(0xffffffff) << (BMP_BIT - 32) | BMP_C(0x7f) >> (39 - BMP_BIT),
	BMP_C(0xff) << (BMP_BIT * 2 - 40),
};
static const bmp_t b40b[] = {
	BMP_C(0xd4164fc6) << (BMP_BIT - 32) | BMP_C(0x23) >> (39 - BMP_BIT),
	BMP_C(0x46) << (BMP_BIT * 2 - 40),
};
static const bmp_t b40c[] = {
	BMP_C(0xc4ff8071) << (BMP_BIT - 32) | BMP_C(0x7f) >> (39 - BMP_BIT),
	BMP_C(0xff) << (BMP_BIT * 2 - 40),
};
#    endif /* BMP_BIT */

#    if BMP_BIT >= 64
static const bmp_t b64[] = {
	BMP_C(0x000000000000001b) << (BMP_BIT - 64),
};
static const bmp_t b64a[] = {
	BMP_C(0xffffffffffffffff) << (BMP_BIT - 64),
};
static const bmp_t b64b[] = {
	BMP_C(0xb90956c775a41001) << (BMP_BIT - 64),
};
static const bmp_t b64c[] = {
	BMP_C(0x5300000000000000) << (BMP_BIT - 64),
};
static const bmp_t b64d[] = {
	BMP_C(0x42f0e1eba9ea3693) << (BMP_BIT - 64),
};
static const bmp_t b64e[] = {
	BMP_C(0x6c40df5f0b497347) << (BMP_BIT - 64),
};
static const bmp_t b64f[] = {
	BMP_C(0x62ec59e3f1a4f00a) << (BMP_BIT - 64),
};
static const bmp_t b64g[] = {
	BMP_C(0xfcacbebd5931a992) << (BMP_BIT - 64),
};
static const bmp_t b64h[] = {
	BMP_C(0x995dc9bbdf1939fa) << (BMP_BIT - 64),
};
static const bmp_t b64i[] = {
	BMP_C(0x49958c9abd7d353f) << (BMP_BIT - 64),
};
#    else /* BMP_BIT */
static const bmp_t b64[] = {
	BMP_C(0x00000000) << (BMP_BIT - 32) | BMP_C(0x0000000d) >> (63 - BMP_BIT),
	BMP_C(0x0000001b) << (BMP_BIT * 2 - 64),
};
static const bmp_t b64a[] = {
	BMP_C(0xffffffff) << (BMP_BIT - 32) | BMP_C(0x7fffffff) >> (63 - BMP_BIT),
	BMP_C(0xffffffff) << (BMP_BIT * 2 - 64),
};
static const bmp_t b64b[] = {
	BMP_C(0xb90956c7) << (BMP_BIT - 32) | BMP_C(0x3ad20800) >> (63 - BMP_BIT),
	BMP_C(0x75a41001) << (BMP_BIT * 2 - 64),
};
static const bmp_t b64c[] = {
	BMP_C(0x53000000) << (BMP_BIT - 32) | BMP_C(0x00000000) >> (63 - BMP_BIT),
	BMP_C(0x00000000) << (BMP_BIT * 2 - 64),
};
static const bmp_t b64d[] = {
	BMP_C(0x42f0e1eb) << (BMP_BIT - 32) | BMP_C(0x54f51b49) >> (63 - BMP_BIT),
	BMP_C(0xa9ea3693) << (BMP_BIT * 2 - 64),
};
static const bmp_t b64e[] = {
	BMP_C(0x6c40df5f) << (BMP_BIT - 32) | BMP_C(0x05a4b9a3) >> (63 - BMP_BIT),
	BMP_C(0x0b497347) << (BMP_BIT * 2 - 64),
};
static const bmp_t b64f[] = {
	BMP_C(0x62ec59e3) << (BMP_BIT - 32) | BMP_C(0x78d27805) >> (63 - BMP_BIT),
	BMP_C(0xf1a4f00a) << (BMP_BIT * 2 - 64),
};
static const bmp_t b64g[] = {
	BMP_C(0xfcacbebd) << (BMP_BIT - 32) | BMP_C(0x2c98d4c9) >> (63 - BMP_BIT),
	BMP_C(0x5931a992) << (BMP_BIT * 2 - 64),
};
static const bmp_t b64h[] = {
	BMP_C(0x995dc9bb) << (BMP_BIT - 32) | BMP_C(0x6f8c9cfd) >> (63 - BMP_BIT),
	BMP_C(0xdf1939fa) << (BMP_BIT * 2 - 64),
};
static const bmp_t b64i[] = {
	BMP_C(0x49958c9a) << (BMP_BIT - 32) | BMP_C(0x5ebe9a9f) >> (63 - BMP_BIT),
	BMP_C(0xbd7d353f) << (BMP_BIT * 2 - 64),
};
#    endif /* BMP_BIT */

#    if BMP_BIT >= 82
static const bmp_t b82[] = {
	BMP_C(0x0308c0111011401440411) << (BMP_BIT - 82),
};
static const bmp_t b82a[] = {
	BMP_C(0x09ea83f625023801fd612) << (BMP_BIT - 82),
};
#    elif BMP_BIT >= 41
static const bmp_t b82[] = {
	BMP_C(0x01846008880) << (BMP_BIT - 41) | BMP_C(0x08a00a20208) >> (81 - BMP_BIT),
	BMP_C(0x11401440411) << (BMP_BIT * 2 - 82),
};
static const bmp_t b82a[] = {
	BMP_C(0x04f541fb128) << (BMP_BIT - 41) | BMP_C(0x011c00feb09) >> (81 - BMP_BIT),
	BMP_C(0x023801fd612) << (BMP_BIT * 2 - 82),
};
#    else /* BMP_BIT */
static const bmp_t b82[] = {
	BMP_C(0x0c230044) << (BMP_BIT - 32) | BMP_C(0x040) >> (40 - BMP_BIT),
	BMP_C(0x40450051) << (BMP_BIT * 2 - 64) | BMP_C(0x00104) >> (80 - BMP_BIT * 2),
	BMP_C(0x00411) << (BMP_BIT * 3 - 82),
};
static const bmp_t b82a[] = {
	BMP_C(0x27aa0fd8) << (BMP_BIT - 32) | BMP_C(0x094) >> (40 - BMP_BIT),
	BMP_C(0x9408e007) << (BMP_BIT * 2 - 64) | BMP_C(0x0f584) >> (80 - BMP_BIT * 2),
	BMP_C(0x3d612) << (BMP_BIT * 3 - 82),
};
#    endif /* BMP_BIT */

/* END AUTO-GENERATED CONSTANTS */
/* DO NOT EDIT the section above, INCLUDING the previous comment. */

/* Array of the polynomial bitmaps used in the model table. */
static const bmp_t b32[] = {
	BMP_C(0x000000af) << (BMP_BIT - 32),	/*   0 -- 32,000000af */
	BMP_C(0x00010000) << (BMP_BIT - 32),	/*   1 -- 16,    0001 */
	BMP_C(0x00020000) << (BMP_BIT - 32),	/*   2 -- 15,    0001 */
	BMP_C(0x00065b00) << (BMP_BIT - 32),	/*   3 -- 24,  00065b */
	BMP_C(0x007e0000) << (BMP_BIT - 32),	/*   4 -- 16,    007e */
	BMP_C(0x007f0000) << (BMP_BIT - 32),	/*   5 -- 16,    007f */
	BMP_C(0x03400000) << (BMP_BIT - 32),	/*   6 -- 11,     01a */
	BMP_C(0x0376e6e7) << (BMP_BIT - 32),	/*   7 -- 32,0376e6e7 */
	BMP_C(0x04c11db7) << (BMP_BIT - 32),	/*   8 -- 32,04c11db7 */
	BMP_C(0x05890000) << (BMP_BIT - 32),	/*   9 -- 16,    0589 */
	BMP_C(0x07000000) << (BMP_BIT - 32),	/*  10 --  8,      07 */
	BMP_C(0x09823b6e) << (BMP_BIT - 32),	/*  11 -- 31,04c11db7 */
	BMP_C(0x0b3c0000) << (BMP_BIT - 32),	/*  12 -- 15,    059e */
	BMP_C(0x0c000000) << (BMP_BIT - 32),	/*  13 --  6,      03 */
	BMP_C(0x0c200000) << (BMP_BIT - 32),	/*  14 -- 11,     061 */
	BMP_C(0x0fb30000) << (BMP_BIT - 32),	/*  15 -- 16,    0fb3 */
	BMP_C(0x10210000) << (BMP_BIT - 32),	/*  16 -- 16,    1021 */
	BMP_C(0x12000000) << (BMP_BIT - 32),	/*  17 --  7,      09 */
	BMP_C(0x130d2afc) << (BMP_BIT - 32),	/*  18 -- 30,04c34abf */
	BMP_C(0x144e6300) << (BMP_BIT - 32),	/*  19 -- 24,  144e63 */
	BMP_C(0x15000000) << (BMP_BIT - 32),	/*  20 --  8,      15 */
	BMP_C(0x1697d06a) << (BMP_BIT - 32),	/*  21 -- 32,1697d06a */
	BMP_C(0x18000000) << (BMP_BIT - 32),	/*  22 --  6,      06 */
	BMP_C(0x19d3c8d8) << (BMP_BIT - 32),	/*  23 -- 31,0ce9e46c */
	BMP_C(0x1c000000) << (BMP_BIT - 32),	/*  24 --  6,      07 */
	BMP_C(0x1d000000) << (BMP_BIT - 32),	/*  25 --  8,      1d */
	BMP_C(0x1d0f0000) << (BMP_BIT - 32),	/*  26 -- 16,    1d0f */
	BMP_C(0x1dcf0000) << (BMP_BIT - 32),	/*  27 -- 16,    1dcf */
	BMP_C(0x1edc6f41) << (BMP_BIT - 32),	/*  28 -- 32,1edc6f41 */
	BMP_C(0x1f23b800) << (BMP_BIT - 32),	/*  29 -- 24,  1f23b8 */
	BMP_C(0x20000000) << (BMP_BIT - 32),	/*  30 --  4,       2 */
	BMP_C(0x20140000) << (BMP_BIT - 32),	/*  31 -- 14,    0805 */
	BMP_C(0x20b40000) << (BMP_BIT - 32),	/*  32 -- 14,    082d */
	BMP_C(0x20fe0000) << (BMP_BIT - 32),	/*  33 -- 16,    20fe */
	BMP_C(0x21890000) << (BMP_BIT - 32),	/*  34 -- 16,    2189 */
	BMP_C(0x21cf0200) << (BMP_BIT - 32),	/*  35 -- 24,  21cf02 */
	BMP_C(0x23ef5200) << (BMP_BIT - 32),	/*  36 -- 24,  23ef52 */
	BMP_C(0x25000000) << (BMP_BIT - 32),	/*  37 --  8,      25 */
	BMP_C(0x26b10000) << (BMP_BIT - 32),	/*  38 -- 16,    26b1 */
	BMP_C(0x27d00000) << (BMP_BIT - 32),	/*  39 -- 13,    04fa */
	BMP_C(0x28000000) << (BMP_BIT - 32),	/*  40 --  5,      05 */
	BMP_C(0x29b10000) << (BMP_BIT - 32),	/*  41 -- 16,    29b1 */
	BMP_C(0x2f000000) << (BMP_BIT - 32),	/*  42 --  8,      2f */
	BMP_C(0x30000000) << (BMP_BIT - 32),	/*  43 --  4, 3/ 5, 6 */
	BMP_C(0x3010bf7f) << (BMP_BIT - 32),	/*  44 -- 32,3010bf7f */
	BMP_C(0x31000000) << (BMP_BIT - 32),	/*  45 --  8,      31 */
	BMP_C(0x31c30000) << (BMP_BIT - 32),	/*  46 -- 16,    31c3 */
	BMP_C(0x328b6300) << (BMP_BIT - 32),	/*  47 -- 24,  328b63 */
	BMP_C(0x34000000) << (BMP_BIT - 32),	/*  48 --  6,      0d */
	BMP_C(0x340bc6d9) << (BMP_BIT - 32),	/*  49 -- 32,340bc6d9 */
	BMP_C(0x38000000) << (BMP_BIT - 32),	/*  50 --  5,      07 */
	BMP_C(0x39000000) << (BMP_BIT - 32),	/*  51 --  8,      39 */
	BMP_C(0x3d650000) << (BMP_BIT - 32),	/*  52 -- 16,    3d65 */
	BMP_C(0x3e000000) << (BMP_BIT - 32),	/*  53 --  8,      3e */
	BMP_C(0x42000000) << (BMP_BIT - 32),	/*  54 --  8,      42 */
	BMP_C(0x44c20000) << (BMP_BIT - 32),	/*  55 -- 16,    44c2 */
	BMP_C(0x45270551) << (BMP_BIT - 32),	/*  56 -- 32,45270551 */
	BMP_C(0x48000000) << (BMP_BIT - 32),	/*  57 --  5,      09 */
	BMP_C(0x4acc0000) << (BMP_BIT - 32),	/*  58 -- 15,    2566 */
	BMP_C(0x4b000000) << (BMP_BIT - 32),	/*  59 --  8,      4b */
	BMP_C(0x4b370000) << (BMP_BIT - 32),	/*  60 -- 16,    4b37 */
	BMP_C(0x4c060000) << (BMP_BIT - 32),	/*  61 -- 16,    4c06 */
	BMP_C(0x55000000) << (BMP_BIT - 32),	/*  62 --  8,      55 */
	BMP_C(0x55555500) << (BMP_BIT - 32),	/*  63 -- 24,  555555 */
	BMP_C(0x59350000) << (BMP_BIT - 32),	/*  64 -- 16,    5935 */
	BMP_C(0x5d380000) << (BMP_BIT - 32),	/*  65 -- 16,    5d38 */
	BMP_C(0x5d6dcb00) << (BMP_BIT - 32),	/*  66 -- 24,  5d6dcb */
	BMP_C(0x60000000) << (BMP_BIT - 32),	/*  67 --  3,       3 */
	BMP_C(0x60e00000) << (BMP_BIT - 32),	/*  68 -- 11,     307 */
	BMP_C(0x63d00000) << (BMP_BIT - 32),	/*  69 -- 16,    63d0 */
	BMP_C(0x64000000) << (BMP_BIT - 32),	/*  70 --  6,      19 */
	BMP_C(0x66400000) << (BMP_BIT - 32),	/*  71 -- 10,     199 */
	BMP_C(0x66c50000) << (BMP_BIT - 32),	/*  72 -- 16,    66c5 */
	BMP_C(0x6f630000) << (BMP_BIT - 32),	/*  73 -- 16,    6f63 */
	BMP_C(0x6f910000) << (BMP_BIT - 32),	/*  74 -- 16,    6f91 */
	BMP_C(0x70000000) << (BMP_BIT - 32),	/*  75 --  4,       7 */
	BMP_C(0x70a00000) << (BMP_BIT - 32),	/*  76 -- 11,     385 */
	BMP_C(0x755b0000) << (BMP_BIT - 32),	/*  77 -- 16,    755b */
	BMP_C(0x765e7680) << (BMP_BIT - 32),	/*  78 -- 32,765e7680 */
	BMP_C(0x7979bd00) << (BMP_BIT - 32),	/*  79 -- 24,  7979bd */
	BMP_C(0x7e000000) << (BMP_BIT - 32),	/*  80 --  8,      7e */
	BMP_C(0x80006300) << (BMP_BIT - 32),	/*  81 -- 24,  800063 */
	BMP_C(0x80050000) << (BMP_BIT - 32),	/*  82 -- 16,    8005 */
	BMP_C(0x800d0000) << (BMP_BIT - 32),	/*  83 -- 16,    800d */
	BMP_C(0x80c2e71c) << (BMP_BIT - 32),	/*  84 -- 30,2030b9c7 */
	BMP_C(0x80f00000) << (BMP_BIT - 32),	/*  85 -- 12,     80f */
	BMP_C(0x814141ab) << (BMP_BIT - 32),	/*  86 -- 32,814141ab */
	BMP_C(0x864cfb00) << (BMP_BIT - 32),	/*  87 -- 24,  864cfb */
	BMP_C(0x87315576) << (BMP_BIT - 32),	/*  88 -- 32,87315576 */
	BMP_C(0x89ec0000) << (BMP_BIT - 32),	/*  89 -- 16,    89ec */
	BMP_C(0x8a000000) << (BMP_BIT - 32),	/*  90 --  7,      45 */
	BMP_C(0x8b320000) << (BMP_BIT - 32),	/*  91 -- 15,    4599 */
	BMP_C(0x8bb70000) << (BMP_BIT - 32),	/*  92 -- 16,    8bb7 */
	BMP_C(0x8cc00000) << (BMP_BIT - 32),	/*  93 -- 10,     233 */
	BMP_C(0x904cddbf) << (BMP_BIT - 32),	/*  94 -- 32,904cddbf */
	BMP_C(0x906e0000) << (BMP_BIT - 32),	/*  95 -- 16,    906e */
	BMP_C(0x97000000) << (BMP_BIT - 32),	/*  96 --  8,      97 */
	BMP_C(0x98000000) << (BMP_BIT - 32),	/*  97 --  6,      26 */
	BMP_C(0x9b000000) << (BMP_BIT - 32),	/*  98 --  8,      9b */
	BMP_C(0x9c000000) << (BMP_BIT - 32),	/*  99 --  6,      27 */
	BMP_C(0x9d5e4de2) << (BMP_BIT - 32),	/* 100 -- 31,4eaf26f1 */
	BMP_C(0x9e000000) << (BMP_BIT - 32),	/* 101 --  7,      4f */
	BMP_C(0x9ecf0000) << (BMP_BIT - 32),	/* 102 -- 16,    9ecf */
	BMP_C(0xa0970000) << (BMP_BIT - 32),	/* 103 -- 16,    a097 */
	BMP_C(0xa1000000) << (BMP_BIT - 32),	/* 104 --  8,      a1 */
	BMP_C(0xa3660000) << (BMP_BIT - 32),	/* 105 -- 16,    a366 */
	BMP_C(0xa6000000) << (BMP_BIT - 32),	/* 106 --  7,      53 */
	BMP_C(0xa8000000) << (BMP_BIT - 32),	/* 107 --  5,      15 */
	BMP_C(0xa8190000) << (BMP_BIT - 32),	/* 108 -- 16,    a819 */
	BMP_C(0xa833982b) << (BMP_BIT - 32),	/* 109 -- 32,a833982b */
	BMP_C(0xabcdef00) << (BMP_BIT - 32),	/* 110 -- 24,  abcdef */
	BMP_C(0xac000000) << (BMP_BIT - 32),	/* 111 --  8,      ac */
	BMP_C(0xaee70000) << (BMP_BIT - 32),	/* 112 -- 16,    aee7 */
	BMP_C(0xb0000000) << (BMP_BIT - 32),	/* 113 --  4,       b */
	BMP_C(0xb0010000) << (BMP_BIT - 32),	/* 114 -- 16,    b001 */
	BMP_C(0xb2aa0000) << (BMP_BIT - 32),	/* 115 -- 16,    b2aa */
	BMP_C(0xb4600000) << (BMP_BIT - 32),	/* 116 -- 11,     5a3 */
	BMP_C(0xb4c80000) << (BMP_BIT - 32),	/* 117 -- 16,    b4c8 */
	BMP_C(0xb4f3e600) << (BMP_BIT - 32),	/* 118 -- 24,  b4f3e6 */
	BMP_C(0xb704ce00) << (BMP_BIT - 32),	/* 119 -- 24,  b704ce */
	BMP_C(0xb798b438) << (BMP_BIT - 32),	/* 120 -- 32,b798b438 */
	BMP_C(0xbb3d0000) << (BMP_BIT - 32),	/* 121 -- 16,    bb3d */
	BMP_C(0xbc000000) << (BMP_BIT - 32),	/* 122 --  8,      bc */
	BMP_C(0xbd0be338) << (BMP_BIT - 32),	/* 123 -- 32,bd0be338 */
	BMP_C(0xbdf40000) << (BMP_BIT - 32),	/* 124 -- 16,    bdf4 */
	BMP_C(0xbf050000) << (BMP_BIT - 32),	/* 125 -- 16,    bf05 */
	BMP_C(0xc0000000) << (BMP_BIT - 32),	/* 126 --  3,       6 */
	BMP_C(0xc2000000) << (BMP_BIT - 32),	/* 127 --  7,      61 */
	BMP_C(0xc25a5600) << (BMP_BIT - 32),	/* 128 -- 24,  c25a56 */
	BMP_C(0xc2b70000) << (BMP_BIT - 32),	/* 129 -- 16,    c2b7 */
	BMP_C(0xc4000000) << (BMP_BIT - 32),	/* 130 --  8,      c4 */
	BMP_C(0xc6c60000) << (BMP_BIT - 32),	/* 131 -- 16,    c6c6 */
	BMP_C(0xc704dd7b) << (BMP_BIT - 32),	/* 132 -- 32,c704dd7b */
	BMP_C(0xc8000000) << (BMP_BIT - 32),	/* 133 --  5,      19 */
	BMP_C(0xc8670000) << (BMP_BIT - 32),	/* 134 -- 16,    c867 */
	BMP_C(0xcbf43926) << (BMP_BIT - 32),	/* 135 -- 32,cbf43926 */
	BMP_C(0xcde70300) << (BMP_BIT - 32),	/* 136 -- 24,  cde703 */
	BMP_C(0xd0000000) << (BMP_BIT - 32),	/* 137 --  8,      d0 */
	BMP_C(0xd02a0000) << (BMP_BIT - 32),	/* 138 -- 15,    6815 */
	BMP_C(0xd0db0000) << (BMP_BIT - 32),	/* 139 -- 16,    d0db */
	BMP_C(0xd3be9568) << (BMP_BIT - 32),	/* 140 -- 30,34efa55a */
	BMP_C(0xd4d00000) << (BMP_BIT - 32),	/* 141 -- 12,     d4d */
	BMP_C(0xd5000000) << (BMP_BIT - 32),	/* 142 --  8,      d5 */
	BMP_C(0xd64e0000) << (BMP_BIT - 32),	/* 143 -- 16,    d64e */
	BMP_C(0xda000000) << (BMP_BIT - 32),	/* 144 --  8,      da */
	BMP_C(0xdaf00000) << (BMP_BIT - 32),	/* 145 -- 12,     daf */
	BMP_C(0xdebb20e3) << (BMP_BIT - 32),	/* 146 -- 32,debb20e3 */
	BMP_C(0xdf000000) << (BMP_BIT - 32),	/* 147 --  8,      df */
	BMP_C(0xe0000000) << (BMP_BIT - 32),	/* 148 --  3,       7 */
	BMP_C(0xe3069283) << (BMP_BIT - 32),	/* 149 -- 32,e3069283 */
	BMP_C(0xe3940000) << (BMP_BIT - 32),	/* 150 -- 16,    e394 */
	BMP_C(0xe5cc0000) << (BMP_BIT - 32),	/* 151 -- 16,    e5cc */
	BMP_C(0xe7a80000) << (BMP_BIT - 32),	/* 152 -- 13,    1cf5 */
	BMP_C(0xea000000) << (BMP_BIT - 32),	/* 153 --  7,      75 */
	BMP_C(0xea820000) << (BMP_BIT - 32),	/* 154 -- 16,    ea82 */
	BMP_C(0xec000000) << (BMP_BIT - 32),	/* 155 --  6,      3b */
	BMP_C(0xf0000000) << (BMP_BIT - 32),	/* 156 --  4,       f */
	BMP_C(0xf0b80000) << (BMP_BIT - 32),	/* 157 -- 16,    f0b8 */
	BMP_C(0xf1300000) << (BMP_BIT - 32),	/* 158 -- 12,     f13 */
	BMP_C(0xf4000000) << (BMP_BIT - 32),	/* 159 --  8,      f4 */
	BMP_C(0xf4acfb13) << (BMP_BIT - 32),	/* 160 -- 32,f4acfb13 */
	BMP_C(0xf5b00000) << (BMP_BIT - 32),	/* 161 -- 12,     f5b */
	BMP_C(0xf6400000) << (BMP_BIT - 32),	/* 162 -- 10,     3d9 */
	BMP_C(0xf8000000) << (BMP_BIT - 32),	/* 163 --  5,      1f */
	BMP_C(0xfc000000) << (BMP_BIT - 32),	/* 164 --  6,      3f */
	BMP_C(0xfc891918) << (BMP_BIT - 32),	/* 165 -- 32,fc891918 */
	BMP_C(0xfd000000) << (BMP_BIT - 32),	/* 166 --  8,      fd */
	BMP_C(0xfe000000) << (BMP_BIT - 32),	/* 167 --  7,      7f */
	BMP_C(0xfedcba00) << (BMP_BIT - 32),	/* 168 -- 24,  fedcba */
	BMP_C(0xfee80000) << (BMP_BIT - 32),	/* 169 -- 16,    fee8 */
	BMP_C(0xff000000) << (BMP_BIT - 32),	/* 170 --  8,      ff */
	BMP_C(0xffc00000) << (BMP_BIT - 32),	/* 171 -- 10,     3ff */
	BMP_C(0xfff00000) << (BMP_BIT - 32),	/* 172 -- 12,     fff */
	BMP_C(0xffff0000) << (BMP_BIT - 32),	/* 173 -- 16,    ffff */
	BMP_C(0xffffff00) << (BMP_BIT - 32),	/* 174 -- 24,  ffffff */
	BMP_C(0xfffffffc) << (BMP_BIT - 32),	/* 175 -- 30,3fffffff */
	BMP_C(0xfffffffe) << (BMP_BIT - 32),	/* 176 -- 31,7fffffff */
	BMP_C(0xffffffff) << (BMP_BIT - 32),	/* 177 -- 32,ffffffff */
};

static const struct malias aliases[];

/* Table of preset CRC models.
 * Sorted by left-justified polynomial for bsearch().
 */
static const struct mpreset models[] = {
	{64UL, b64,     b64a,    P_LE,   b64a,    b64b,    b64c,    aliases+ 91},	/*  0 */
	{32UL, b32+  0, 0,       P_BE,   0,       b32+123, 0,       aliases+126},	/*  1 */
	{40UL, b40,     0,       P_BE,   b40a,    b40b,    b40c,    aliases+ 80},	/*  2 */
	{24UL, b32+  3, b32+ 63, P_LE,   0,       b32+128, 0,       aliases+ 54},	/*  3 */
	{32UL, b32+  8, 0,       P_BE,   b32+177, b32+ 78, b32+132, aliases+ 74},	/*  4 */
	{32UL, b32+  8, b32+177, P_BE,   0,       b32+  7, 0,       aliases+ 73},	/*  5 */
	{32UL, b32+  8, b32+177, P_BE,   b32+177, b32+165, b32+132, aliases+ 68},	/*  6 */
	{32UL, b32+  8, b32+177, P_LE,   0,       b32+ 49, 0,       aliases+118},	/*  7 */
	{32UL, b32+  8, b32+177, P_LE,   b32+177, b32+135, b32+146, aliases+ 64},	/*  8 */
	{16UL, b32+  9, 0,       P_BE,   0,       b32+  5, 0,       aliases+ 28},	/*  9 */
	{16UL, b32+  9, 0,       P_BE,   b32+  1, b32+  4, b32+  9, aliases+ 27},	/* 10 */
	{ 8UL, b32+ 10, 0,       P_BE,   0,       b32+159, 0,       aliases+ 97},	/* 11 */
	{ 8UL, b32+ 10, 0,       P_BE,   b32+ 62, b32+104, b32+111, aliases+105},	/* 12 */
	{ 8UL, b32+ 10, b32+170, P_LE,   0,       b32+137, 0,       aliases+109},	/* 13 */
	{31UL, b32+ 11, b32+176, P_BE,   b32+176, b32+ 23, b32+100, aliases+ 63},	/* 14 */
	{ 6UL, b32+ 13, 0,       P_LE,   0,       b32+ 22, 0,       aliases+ 87},	/* 15 */
	{82UL, b82,     0,       P_LE,   0,       b82a,    0,       aliases+112},	/* 16 */
	{16UL, b32+ 16, 0,       P_BE,   0,       b32+ 46, 0,       aliases+127},	/* 17 */
	{16UL, b32+ 16, 0,       P_LE,   0,       b32+ 34, 0,       aliases+119},	/* 18 */
	{16UL, b32+ 16, b32+ 26, P_BE,   0,       b32+151, 0,       aliases+ 18},	/* 19 */
	{16UL, b32+ 16, b32+ 89, P_LE,   0,       b32+ 38, 0,       aliases+ 49},	/* 20 */
	{16UL, b32+ 16, b32+115, P_LE,   0,       b32+ 69, 0,       aliases+ 45},	/* 21 */
	{16UL, b32+ 16, b32+131, P_LE,   0,       b32+125, 0,       aliases+113},	/* 22 */
	{16UL, b32+ 16, b32+173, P_BE,   0,       b32+ 41, 0,       aliases+ 21},	/* 23 */
	{16UL, b32+ 16, b32+173, P_BE,   b32+173, b32+143, b32+ 26, aliases+ 32},	/* 24 */
	{16UL, b32+ 16, b32+173, P_LE,   0,       b32+ 74, 0,       aliases+ 41},	/* 25 */
	{16UL, b32+ 16, b32+173, P_LE,   b32+173, b32+ 95, b32+157, aliases+123},	/* 26 */
	{ 7UL, b32+ 17, 0,       P_BE,   0,       b32+153, 0,       aliases+ 94},	/* 27 */
	{ 6UL, b32+ 24, b32+164, P_BE,   0,       b32+155, 0,       aliases+ 85},	/* 28 */
	{ 8UL, b32+ 25, b32+166, P_BE,   0,       b32+ 80, 0,       aliases+104},	/* 29 */
	{ 8UL, b32+ 25, b32+170, P_BE,   b32+170, b32+ 59, b32+130, aliases+110},	/* 30 */
	{ 8UL, b32+ 25, b32+170, P_LE,   0,       b32+ 96, 0,       aliases+103},	/* 31 */
	{16UL, b32+ 27, b32+173, P_BE,   b32+173, b32+108, b32+150, aliases+ 44},	/* 32 */
	{32UL, b32+ 28, b32+177, P_LE,   b32+177, b32+149, b32+120, aliases+ 75},	/* 33 */
	{14UL, b32+ 31, 0,       P_LE,   0,       b32+ 32, 0,       aliases+ 12},	/* 34 */
	{ 5UL, b32+ 40, b32+163, P_LE,   b32+163, b32+133, b32+ 43, aliases+ 83},	/* 35 */
	{ 8UL, b32+ 42, 0,       P_BE,   0,       b32+ 53, 0,       aliases+108},	/* 36 */
	{ 8UL, b32+ 42, b32+170, P_BE,   b32+170, b32+147, b32+ 54, aliases+ 99},	/* 37 */
	{ 4UL, b32+ 43, 0,       P_LE,   0,       b32+ 75, 0,       aliases+ 79},	/* 38 */
	{ 4UL, b32+ 43, b32+156, P_BE,   b32+156, b32+113, b32+ 30, aliases+ 78},	/* 39 */
	{ 8UL, b32+ 45, 0,       P_LE,   0,       b32+104, 0,       aliases+107},	/* 40 */
	{24UL, b32+ 47, b32+174, P_BE,   b32+174, b32+118, b32+ 19, aliases+ 57},	/* 41 */
	{ 8UL, b32+ 51, 0,       P_LE,   0,       b32+ 20, 0,       aliases+101},	/* 42 */
	{16UL, b32+ 52, 0,       P_BE,   b32+173, b32+129, b32+105, aliases+ 30},	/* 43 */
	{16UL, b32+ 52, 0,       P_LE,   b32+173, b32+154, b32+ 72, aliases+ 29},	/* 44 */
	{64UL, b64d,    0,       P_BE,   0,       b64e,    0,       aliases+ 88},	/* 45 */
	{64UL, b64d,    b64a,    P_BE,   b64a,    b64f,    b64g,    aliases+ 92},	/* 46 */
	{64UL, b64d,    b64a,    P_LE,   b64a,    b64h,    b64i,    aliases+ 93},	/* 47 */
	{ 5UL, b32+ 57, b32+ 57, P_BE,   0,       0,       0,       aliases+ 81},	/* 48 */
	{16UL, b32+ 64, 0,       P_BE,   0,       b32+ 65, 0,       aliases+ 42},	/* 49 */
	{24UL, b32+ 66, b32+110, P_BE,   0,       b32+ 29, 0,       aliases+ 56},	/* 50 */
	{24UL, b32+ 66, b32+168, P_BE,   0,       b32+ 79, 0,       aliases+ 55},	/* 51 */
	{ 3UL, b32+ 67, b32+148, P_LE,   0,       b32+126, 0,       aliases+ 61},	/* 52 */
	{11UL, b32+ 68, 0,       P_BE,   0,       b32+ 14, 0,       aliases+  6},	/* 53 */
	{ 6UL, b32+ 70, 0,       P_LE,   0,       b32+ 97, 0,       aliases+ 86},	/* 54 */
	{16UL, b32+ 73, 0,       P_BE,   0,       b32+124, 0,       aliases+ 38},	/* 55 */
	{11UL, b32+ 76, b32+  6, P_BE,   0,       b32+116, 0,       aliases+  5},	/* 56 */
	{16UL, b32+ 77, 0,       P_BE,   0,       b32+ 33, 0,       aliases+ 43},	/* 57 */
	{24UL, b32+ 81, 0,       P_BE,   0,       b32+ 36, 0,       aliases+ 59},	/* 58 */
	{16UL, b32+ 82, 0,       P_BE,   0,       b32+169, 0,       aliases+ 19},	/* 59 */
	{16UL, b32+ 82, 0,       P_LE,   0,       b32+121, 0,       aliases+  0},	/* 60 */
	{16UL, b32+ 82, 0,       P_LE,   b32+173, b32+ 55, b32+114, aliases+ 40},	/* 61 */
	{16UL, b32+ 82, b32+ 83, P_BE,   0,       b32+102, 0,       aliases+ 26},	/* 62 */
	{16UL, b32+ 82, b32+173, P_BE,   0,       b32+112, 0,       aliases+ 24},	/* 63 */
	{16UL, b32+ 82, b32+173, P_LE,   0,       b32+ 60, 0,       aliases+120},	/* 64 */
	{16UL, b32+ 82, b32+173, P_LE,   b32+173, b32+117, b32+114, aliases+ 51},	/* 65 */
	{30UL, b32+ 84, b32+175, P_BE,   b32+175, b32+ 18, b32+140, aliases+ 62},	/* 66 */
	{12UL, b32+ 85, 0,       P_BE,   0,       b32+161, 0,       aliases+  9},	/* 67 */
	{12UL, b32+ 85, 0,       P_BELE, 0,       b32+145, 0,       aliases+ 10},	/* 68 */
	{32UL, b32+ 86, 0,       P_BE,   0,       b32+ 44, 0,       aliases+ 77},	/* 69 */
	{24UL, b32+ 87, 0,       P_BE,   0,       b32+136, 0,       aliases+ 58},	/* 70 */
	{24UL, b32+ 87, b32+119, P_BE,   0,       b32+ 35, 0,       aliases+ 53},	/* 71 */
	{ 7UL, b32+ 90, 0,       P_BE,   0,       b32+127, 0,       aliases+ 96},	/* 72 */
	{15UL, b32+ 91, 0,       P_BE,   0,       b32+ 12, 0,       aliases+ 13},	/* 73 */
	{16UL, b32+ 92, 0,       P_BE,   0,       b32+139, 0,       aliases+ 47},	/* 74 */
	{10UL, b32+ 93, 0,       P_BE,   0,       b32+ 71, 0,       aliases+  3},	/* 75 */
	{ 8UL, b32+ 98, 0,       P_BE,   0,       b32+153, 0,       aliases+106},	/* 76 */
	{ 8UL, b32+ 98, 0,       P_LE,   0,       b32+ 37, 0,       aliases+111},	/* 77 */
	{ 8UL, b32+ 98, b32+170, P_BE,   0,       b32+144, 0,       aliases+100},	/* 78 */
	{ 6UL, b32+ 99, b32+164, P_BE,   0,       b32+ 48, 0,       aliases+ 84},	/* 79 */
	{ 7UL, b32+101, b32+167, P_LE,   0,       b32+106, 0,       aliases+ 95},	/* 80 */
	{16UL, b32+103, 0,       P_BE,   0,       b32+ 15, 0,       aliases+ 48},	/* 81 */
	{ 5UL, b32+107, 0,       P_LE,   0,       b32+ 50, 0,       aliases+ 82},	/* 82 */
	{32UL, b32+109, b32+177, P_LE,   b32+177, b32+ 88, b32+ 56, aliases+ 76},	/* 83 */
	{16UL, b32+134, b32+173, P_BE,   0,       b32+ 61, 0,       aliases+ 23},	/* 84 */
	{15UL, b32+138, 0,       P_BE,   b32+  2, b32+ 58, b32+138, aliases+ 14},	/* 85 */
	{ 8UL, b32+142, 0,       P_BE,   0,       b32+122, 0,       aliases+102},	/* 86 */
	{13UL, b32+152, 0,       P_BE,   0,       b32+ 39, 0,       aliases+ 11},	/* 87 */
	{12UL, b32+158, b32+172, P_BE,   0,       b32+141, 0,       aliases+  8},	/* 88 */
	{32UL, b32+160, b32+177, P_LE,   b32+177, b32+ 21, b32+ 94, aliases+ 67},	/* 89 */
	{10UL, b32+162, b32+171, P_BE,   0,       b32+ 93, 0,       aliases+  4},	/* 90 */
	{ 0UL, 0,       0,       P_BE,   0,       0,       0,       NULL       },	/* terminating entry */
};
#    define NPRESETS 91

/* List of names with pointers to models, pre-sorted for use with bsearch() */
static const struct malias aliases[] = {
	{"ARC",			models+60},	/*   0 */
	{"B-CRC-32",		models+ 6},	/*   1 */
	{"CKSUM",		models+ 4},	/*   2 */
	{"CRC-10",		models+75},	/*   3 */
	{"CRC-10/CDMA2000",	models+90},	/*   4 */
	{"CRC-11",		models+56},	/*   5 */
	{"CRC-11/UMTS",		models+53},	/*   6 */
	{"CRC-12/3GPP",		models+68},	/*   7 */
	{"CRC-12/CDMA2000",	models+88},	/*   8 */
	{"CRC-12/DECT",		models+67},	/*   9 */
	{"CRC-12/UMTS",		models+68},	/*  10 */
	{"CRC-13/BBC",		models+87},	/*  11 */
	{"CRC-14/DARC",		models+34},	/*  12 */
	{"CRC-15",		models+73},	/*  13 */
	{"CRC-15/MPT1327",	models+85},	/*  14 */
	{"CRC-16",		models+60},	/*  15 */
	{"CRC-16/ACORN",	models+17},	/*  16 */
	{"CRC-16/ARC",		models+60},	/*  17 */
	{"CRC-16/AUG-CCITT",	models+19},	/*  18 */
	{"CRC-16/BUYPASS",	models+59},	/*  19 */
	{"CRC-16/CCITT",	models+18},	/*  20 */
	{"CRC-16/CCITT-FALSE",	models+23},	/*  21 */
	{"CRC-16/CCITT-TRUE",	models+18},	/*  22 */
	{"CRC-16/CDMA2000",	models+84},	/*  23 */
	{"CRC-16/CMS",		models+63},	/*  24 */
	{"CRC-16/DARC",		models+24},	/*  25 */
	{"CRC-16/DDS-110",	models+62},	/*  26 */
	{"CRC-16/DECT-R",	models+10},	/*  27 */
	{"CRC-16/DECT-X",	models+ 9},	/*  28 */
	{"CRC-16/DNP",		models+44},	/*  29 */
	{"CRC-16/EN-13757",	models+43},	/*  30 */
	{"CRC-16/EPC",		models+24},	/*  31 */
	{"CRC-16/GENIBUS",	models+24},	/*  32 */
	{"CRC-16/I-CODE",	models+24},	/*  33 */
	{"CRC-16/IBM-SDLC",	models+26},	/*  34 */
	{"CRC-16/IEC-61158-2",	models+32},	/*  35 */
	{"CRC-16/ISO-HDLC",	models+26},	/*  36 */
	{"CRC-16/LHA",		models+60},	/*  37 */
	{"CRC-16/LJ1200",	models+55},	/*  38 */
	{"CRC-16/LTE",		models+17},	/*  39 */
	{"CRC-16/MAXIM",	models+61},	/*  40 */
	{"CRC-16/MCRF4XX",	models+25},	/*  41 */
	{"CRC-16/OPENSAFETY-A",	models+49},	/*  42 */
	{"CRC-16/OPENSAFETY-B",	models+57},	/*  43 */
	{"CRC-16/PROFIBUS",	models+32},	/*  44 */
	{"CRC-16/RIELLO",	models+21},	/*  45 */
	{"CRC-16/SPI-FUJITSU",	models+19},	/*  46 */
	{"CRC-16/T10-DIF",	models+74},	/*  47 */
	{"CRC-16/TELEDISK",	models+81},	/*  48 */
	{"CRC-16/TMS37157",	models+20},	/*  49 */
	{"CRC-16/UMTS",		models+59},	/*  50 */
	{"CRC-16/USB",		models+65},	/*  51 */
	{"CRC-16/VERIFONE",	models+59},	/*  52 */
	{"CRC-24",		models+71},	/*  53 */
	{"CRC-24/BLE",		models+ 3},	/*  54 */
	{"CRC-24/FLEXRAY-A",	models+51},	/*  55 */
	{"CRC-24/FLEXRAY-B",	models+50},	/*  56 */
	{"CRC-24/INTERLAKEN",	models+41},	/*  57 */
	{"CRC-24/LTE-A",	models+70},	/*  58 */
	{"CRC-24/LTE-B",	models+58},	/*  59 */
	{"CRC-24/OPENPGP",	models+71},	/*  60 */
	{"CRC-3/ROHC",		models+52},	/*  61 */
	{"CRC-30/CDMA",		models+66},	/*  62 */
	{"CRC-31/PHILIPS",	models+14},	/*  63 */
	{"CRC-32",		models+ 8},	/*  64 */
	{"CRC-32/AAL5",		models+ 6},	/*  65 */
	{"CRC-32/ADCCP",	models+ 8},	/*  66 */
	{"CRC-32/AUTOSAR",	models+89},	/*  67 */
	{"CRC-32/BZIP2",	models+ 6},	/*  68 */
	{"CRC-32/CASTAGNOLI",	models+33},	/*  69 */
	{"CRC-32/DECT-B",	models+ 6},	/*  70 */
	{"CRC-32/INTERLAKEN",	models+33},	/*  71 */
	{"CRC-32/ISCSI",	models+33},	/*  72 */
	{"CRC-32/MPEG-2",	models+ 5},	/*  73 */
	{"CRC-32/POSIX",	models+ 4},	/*  74 */
	{"CRC-32C",		models+33},	/*  75 */
	{"CRC-32D",		models+83},	/*  76 */
	{"CRC-32Q",		models+69},	/*  77 */
	{"CRC-4/INTERLAKEN",	models+39},	/*  78 */
	{"CRC-4/ITU",		models+38},	/*  79 */
	{"CRC-40/GSM",		models+ 2},	/*  80 */
	{"CRC-5/EPC",		models+48},	/*  81 */
	{"CRC-5/ITU",		models+82},	/*  82 */
	{"CRC-5/USB",		models+35},	/*  83 */
	{"CRC-6/CDMA2000-A",	models+79},	/*  84 */
	{"CRC-6/CDMA2000-B",	models+28},	/*  85 */
	{"CRC-6/DARC",		models+54},	/*  86 */
	{"CRC-6/ITU",		models+15},	/*  87 */
	{"CRC-64",		models+45},	/*  88 */
	{"CRC-64/ECMA-182",	models+45},	/*  89 */
	{"CRC-64/GO-ECMA",	models+47},	/*  90 */
	{"CRC-64/GO-ISO",	models+ 0},	/*  91 */
	{"CRC-64/WE",		models+46},	/*  92 */
	{"CRC-64/XZ",		models+47},	/*  93 */
	{"CRC-7",		models+27},	/*  94 */
	{"CRC-7/ROHC",		models+80},	/*  95 */
	{"CRC-7/UMTS",		models+72},	/*  96 */
	{"CRC-8",		models+11},	/*  97 */
	{"CRC-8/AES",		models+31},	/*  98 */
	{"CRC-8/AUTOSAR",	models+37},	/*  99 */
	{"CRC-8/CDMA2000",	models+78},	/* 100 */
	{"CRC-8/DARC",		models+42},	/* 101 */
	{"CRC-8/DVB-S2",	models+86},	/* 102 */
	{"CRC-8/EBU",		models+31},	/* 103 */
	{"CRC-8/I-CODE",	models+29},	/* 104 */
	{"CRC-8/ITU",		models+12},	/* 105 */
	{"CRC-8/LTE",		models+76},	/* 106 */
	{"CRC-8/MAXIM",		models+40},	/* 107 */
	{"CRC-8/OPENSAFETY",	models+36},	/* 108 */
	{"CRC-8/ROHC",		models+13},	/* 109 */
	{"CRC-8/SAE-J1850",	models+30},	/* 110 */
	{"CRC-8/WCDMA",		models+77},	/* 111 */
	{"CRC-82/DARC",		models+16},	/* 112 */
	{"CRC-A",		models+22},	/* 113 */
	{"CRC-B",		models+26},	/* 114 */
	{"CRC-CCITT",		models+18},	/* 115 */
	{"CRC-IBM",		models+60},	/* 116 */
	{"DOW-CRC",		models+40},	/* 117 */
	{"JAMCRC",		models+ 7},	/* 118 */
	{"KERMIT",		models+18},	/* 119 */
	{"MODBUS",		models+64},	/* 120 */
	{"PKZIP",		models+ 8},	/* 121 */
	{"R-CRC-16",		models+10},	/* 122 */
	{"X-25",		models+26},	/* 123 */
	{"X-CRC-12",		models+67},	/* 124 */
	{"X-CRC-16",		models+ 9},	/* 125 */
	{"XFER",		models+ 1},	/* 126 */
	{"XMODEM",		models+17},	/* 127 */
	{"ZMODEM",		models+17},	/* 128 */
	{NULL,			NULL     },	/* terminating entry */
};
#    define NALIASES 129

#  endif /* BMP_BIT */
#else /* PRESETS */

static const struct mpreset models[] = {
	{ 0UL, 0,       0,       P_BE,   0,       0,       0,       NULL       },	/* terminating entry */
};
#  define NPRESETS 0

static const struct malias aliases[] = {
	{NULL,			NULL     },	/* terminating entry */
};
#  define NALIASES 0

#endif /* PRESETS */

static void munpack(model_t *, const struct mpreset *);

/* copy a parameter of a preset to a poly */

#define PUNPACK(poly, preset, field) {\
	unsigned long iter, idx; \
	palloc((poly), (preset)->width); \
	if((preset)->field) \
		for(iter=0UL, idx=0UL; \
			iter < (poly)->length; \
			iter += BMP_BIT, ++idx) \
			(poly)->bitmap[idx] = (preset)->field[idx]; \
}

/* copy a parameter of a preset into a model */
#define MUNPACK(parm) PUNPACK(&dest->parm, src, b##parm)

/* Definitions */

int
mbynam(model_t *dest, const char *key) {
	/* Sets parameters in dest according to the model named by key.
	 */
	size_t left = 0, right = NALIASES, middle = 0;
	int cmp = 1;
	char *ukey, *uptr;

	if(!aliases->name)
		return(-1);
	if(!(ukey = malloc((size_t) 1 + strlen(key))))
		uerror("cannot allocate memory for comparison string");
	uptr = ukey;
	do
		*uptr++ = toupper(*key);
	while(*key++);

	while(left < right && cmp) {
		middle = (left >> 1) + (right >> 1);
		cmp = strcmp(ukey, aliases[middle].name);
		if(cmp < 0) right = middle;
		else if(cmp > 0) left = middle + 1;
	}
	free(ukey);

	if(cmp)
		return(0);
	munpack(dest, aliases[middle].model);
	return(1);
}

void
mbynum(model_t *dest, int num) {
	/* Sets parameters in dest according to the model indexed by num. */
	if(num > NPRESETS)
		num = NPRESETS;
	munpack(dest, num+models);
}

int
mcount(void) {
	/* Returns the number of preset models. */
	return(NPRESETS);
}

char *
mnames(void) {
	/* Returns a malloc()-ed string of the names of all preset
	 * models, separated by newlines and terminated by NULL.
	 * Aliases are not listed.
	 */
	size_t size = 0;
	char *string, *sptr;
	const struct malias *aptr = aliases;

	while(aptr->name) {
		if(aptr == aptr->model->alias)
			size += strlen(aptr->name) + 1;
		++aptr;
	}
	if(!size) return(NULL);
	if((string = malloc(size))) {
		aptr = aliases;
		sptr = string;
		while(aptr->name) {
			if(aptr == aptr->model->alias) {
				strcpy(sptr, aptr->name);
				sptr += strlen(aptr->name);
				*sptr++ = '\n';
			}
			++aptr;
		}
		*--sptr = '\0';
	} else
		uerror("cannot allocate memory for list of models");

	return(string);
}

void
mmatch(model_t *model, int flags) {
	/* searches models[] for a model matching the argument, and links a name if found
	 * if flags & M_OVERWR, copies the found model onto the argument. */
	size_t left = 0, right = NPRESETS, middle = 0;
	poly_t poly = PZERO;
	int cmp = 1;
	if(!model) return;

	while(left < right && cmp) {
		middle = (left >> 1) + (right >> 1);
		PUNPACK(&poly, models+middle, bspoly);
		cmp = psncmp(&model->spoly, &poly);
		if(!cmp) {
			PUNPACK(&poly, models+middle, binit);
			cmp = psncmp(&model->init, &poly);
		}
		if(!cmp) {
			if((model->flags & P_REFIN) && (~models[middle].flags & P_REFIN))
				cmp = 1;
			else if((~model->flags & P_REFIN) && (models[middle].flags & P_REFIN))
				cmp = -1;
			else if((model->flags & P_REFOUT) && (~models[middle].flags & P_REFOUT))
				cmp = 1;
			else if((~model->flags & P_REFOUT) && (models[middle].flags & P_REFOUT))
				cmp = -1;
			else {
				PUNPACK(&poly, models+middle, bxorout);
				cmp = psncmp(&model->xorout, &poly);
			}
		}
		if(cmp < 0) right = middle;
		else if(cmp > 0) left = middle + 1;
	}
	pfree(&poly);

	if(!cmp) {
		model->name = models[middle].alias->name;
		if(flags & M_OVERWR)
			munpack(model, models+middle);
	}
}

/* Private functions */

static void
munpack(model_t *dest, const struct mpreset *src) {
	/* Copies the parameters of src to dest.
	 * dest must be an initialised model.
	 */
	if(!dest || !src) return;
	MUNPACK(spoly);
	MUNPACK(init);
	MUNPACK(xorout);
	MUNPACK(check);
	MUNPACK(magic);
	dest->flags = src->flags;
	/* link to the name as it is static */
	dest->name = (src->alias) ? src->alias->name : NULL;
}

#ifdef PRETST
int
main(int argc, char *argv[]) {
	/* check models[] and aliases[] are in order */
	model_t a = MZERO, b = MZERO, n = MZERO;
	const struct mpreset *model = models;
	const struct malias *alias = aliases;

	munpack(&a, model);
	while(plen(a.spoly)) {
		munpack(&b, ++model);
		if(plen(b.spoly) && mcmp(&a, &b) >= 0) {
			fprintf(stderr, "reveng: coding error.  Models "
				"'%s' and '%s' out of order.\n",
				a.name, b.name);
			mfree(&b);
			mfree(&a);
			exit(EXIT_FAILURE);
		}
		mfree(&a);
		a=b;
		b=n;
	}
	/* a is the empty model, no need for mfree() */

	while(alias[0].name && alias[1].name) {
		if(strcmp(alias[0].name, alias[1].name) >= 0) {
			fprintf(stderr, "reveng: coding error.  Aliases "
				"'%s' and '%s' out of order.\n",
				alias[0].name, alias[1].name);
			exit(EXIT_FAILURE);
		}
		++alias;
	}
	exit(EXIT_SUCCESS);
}

void
uerror(const char *msg) {
	/* Callback function to report fatal errors */
	fprintf(stderr, "reveng: %s\n", msg);
	exit(EXIT_FAILURE);
}

#endif /* PRETST */
